apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: qicoo-api-production-canary
  namespace: production
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qicoo-api-production
    spec:
      containers:
      - image: cndjp/qicoo-api
        name: qicoo-api-production
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 1
          successThreshold: 2
          failureThreshold: 2
        resources:
          requests:
            memory: 1024Mi
            cpu: 1000m
          limits:
            memory: 1024Mi
            cpu: 1000m
        envFrom:
        - secretRef:
            name: qicoo-api-secret-production
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
