apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-qicoo-api
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qicoo-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qicoo-api
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: qicoo-api-secret-production
        image: cndjp/qicoo-api:canarytest_0.0.8
        livenessProbe:
          failureThreshold: 2
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        name: qicoo-api
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          failureThreshold: 2
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 30
          successThreshold: 2
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 200m
            memory: 1024Mi
          requests:
            cpu: 200m
            memory: 1024Mi
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
