apiVersion: apps/v1
kind: Deployment
metadata:
  name: qicoo-api
  namespace: qicoo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: qicoo-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: qicoo-api
    spec:
      containers:
        - command:
            - /bin/bash
            - -cx
            - exec /run.sh mysqlrouter
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MYSQL_PASSWORD
                  name: qicoo-secret
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: MYSQL_USER
                  name: qicoo-secret
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PORT
                  name: qicoo-api-config
            - name: MYSQL_HOST
              value: mysql-qicoo2db-0.mysql-cluster.svc.cluster.local
            - name: MYSQL_INNODB_NUM_MEMBERS
              value: "3"
          image: mysql/mysql-router:8.0.12
          name: mysqlrouter
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 102Mi
        - envFrom:
            - configMapRef:
                name: qicoo-api-config
            - secretRef:
                name: qicoo-secret
          image: cndjp/qicoo-api-kt:8d4a887657ae37eb3d8405fccc91a9ddb8f48863
          livenessProbe:
            failureThreshold: 2
            httpGet:
              path: /hc
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 2
            httpGet:
              path: /api/v1/questions
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 30
          name: qicoo-api
          ports:
            - containerPort: 8081
              name: http
          resources:
            limits:
              cpu: 1000m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 102Mi
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 12345
